version: '3.1'
services:
  app:
    build: .
    volumes:
      - ./:/app
    entrypoint:
      - '/bin/bash'
      - '-c'
    command:
      - 'yarn run dev'
    environment:
      - NODE_ENV=development
      - PORT=5000
      - DATABASE_URL=postgres://securitylabs:pass@postgres:5432/securitylabs
    ports:
      - "5000:5000"
    depends_on:
      - postgres

  postgres:
    image: postgres:9.6-alpine
    volumes:
      - ./db/seed.sql:/docker-entrypoint-initdb.d/seed.sql
    environment:
      - POSTGRES_USER=securitylabs
      - POSTGRES_PASSWORD=pass
    ports:
      - "5432:5432"
