version: '3'
services:
  injection:
    build: .
    volumes:
      - $PWD:/app
    entrypoint:
      - '/bin/bash'
      - '-c'
    command:
      - 'yarn run dev injection'
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DATABASE_URL=postgres://securitydemos:pass@postgres:5432/securitydemos
    ports:
      - "3030:3000"
    depends_on:
      - postgres

  postgres:
    image: postgres:9.6-alpine
    volumes:
      - ./db/seed.sql:/docker-entrypoint-initdb.d/seed.sql
    environment:
      - POSTGRES_USER=securitydemos
      - POSTGRES_PASSWORD=pass
